### ISSUE TITLE
Add request timeout

### ISSUE THREAD

**Issue by mgilangjanuar** [mgilangjanuar/pingpong#1]
Please implement request timeout to Axios when requesting the service, adjust the number of timeout in env.

**Comment by diptigandhi24** [comment]
Hey I would like to try this issue

**Comment by diptigandhi24** [comment]
Hey is there a way to test if the timeout is working properly?

**Comment by mgilangjanuar** [comment]
Oh you can make a health check endpoint with infinite loop or delay, maybe 🤔
